--------------------------------------------------------------------------------
-- create_order_types.sql
--------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=STOCKS;

DROP TABLE ORDER_TYPES;
DROP SEQUENCE SEQ_ORDER_TYPES;

CREATE TABLE ORDER_TYPES (
  ID                  NUMBER(10,0) NOT NULL PRIMARY KEY,
  ORDER_TYPE          VARCHAR2(25) NOT NULL,
  DESCRIPTION         VARCHAR2(100) NOT NULL
);

CREATE INDEX order_types_idx01 ON  ORDER_TYPES (order_type);

CREATE SEQUENCE SEQ_ORDER_TYPES
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 23667
  NOCYCLE
  CACHE 10;

INSERT INTO ORDER_TYPES (ID, ORDER_TYPE, DESCRIPTION)
  VALUES (SEQ_ORDER_TYPES.nextval, 'MARKET ORDER', 'ORDER PLACED AT MARKET ORDER PRICE');
INSERT INTO ORDER_TYPES (ID, ORDER_TYPE, DESCRIPTION)
  VALUES (SEQ_ORDER_TYPES.nextval, 'LIMIT ORDER', 'ORDER PLACED AT MAX LIMIT ORDER PRICE');
INSERT INTO ORDER_TYPES (ID, ORDER_TYPE, DESCRIPTION)
  VALUES (SEQ_ORDER_TYPES.nextval, 'STOP LOSS ORDER', 'ORDER PLACED TO PREVENT LOSS');

COMMIT;
