
--------------------------------------------------------------------------------
-- create_application_parameters.sql
--------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=STOCKS;

DROP TABLE APPLICATION_PARAMETERS;
DROP SEQUENCE SEQ_APPLICATION_PARAMETERS;

CREATE TABLE APPLICATION_PARAMETERS (
  ID         NUMBER(10)                          NOT NULL PRIMARY KEY,
  PROP_KEY        VARCHAR2(100)                       NOT NULL,
  PROP_PROPERTY   VARCHAR2(500)                       NOT NULL,
  ENABLED    CHAR(1) DEFAULT 'Y'                 NOT NULL,
  CREATED    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_app_parm_01 ON APPLICATION_PARAMETERS (PROP_KEY);

CREATE SEQUENCE SEQ_APPLICATION_PARAMETERS
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;


INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.application.charsetutf8',
    'UTF-8',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.faultstr.client',
    'client',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.faultstr.server',
    'server',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.request.successful',
    'Request Successful',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.request.failed',
    'Request Failed',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.request.pending',
    'Request Pending',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETERS (ID, PROP_KEY, PROP_PROPERTY, ENABLED, CREATED)
  VALUES (SEQ_APPLICATION_PARAMETERS.nextval,
    'parm.validation.requestheader.source',
    'STOCKTICKER_20170131',
    'Y', CURRENT_TIMESTAMP);

COMMIT;
