--------------------------------------------------------------------------------
-- create_order_status.sql
--------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=STOCKS;

DROP TABLE ORDER_STATUS;
DROP SEQUENCE SEQ_ORDER_STATUS;

CREATE TABLE ORDER_STATUS (
  ID                  NUMBER(10,0) NOT NULL PRIMARY KEY,
  ORDER_STATUS        VARCHAR2(25) NOT NULL,
  DESCRIPTION         VARCHAR2(100) NOT NULL
) TABLESPACE tbs_users_01;

CREATE INDEX order_status_idx01 ON  ORDER_STATUS (order_status);

CREATE SEQUENCE SEQ_ORDER_STATUS
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 23667
  NOCYCLE
  CACHE 10;

INSERT INTO ORDER_STATUS (ID, ORDER_STATUS, DESCRIPTION)
  VALUES (SEQ_ORDER_STATUS.nextval, 'PENDING', 'ORDER IN PENDING STATUS');
INSERT INTO ORDER_STATUS (ID, ORDER_STATUS, DESCRIPTION)
  VALUES (SEQ_ORDER_STATUS.nextval, 'COMPLETED', 'ORDER HAS BEEN COMPLETED');
INSERT INTO ORDER_STATUS (ID, ORDER_STATUS, DESCRIPTION)
  VALUES (SEQ_ORDER_STATUS.nextval, 'CANCELLED', 'ORDER HAS BEEN CANCELLED');

COMMIT;
