--------------------------------------------------------------------------------
-- create_transaction_types.sql
--------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=STOCKS;

DROP TABLE TRANSACTION_TYPES;
DROP SEQUENCE SEQ_TRANSACTION_TYPES;

CREATE TABLE TRANSACTION_TYPES (
  ID                  NUMBER(10,0) NOT NULL PRIMARY KEY,
  TRANSACTION_TYPE    VARCHAR2(25) NOT NULL,
  DESCRIPTION         VARCHAR2(100) NOT NULL
) TABLESPACE tbs_users_01;

CREATE UNIQUE INDEX transaction_type_idx01 ON  TRANSACTION_TYPES (transaction_type);

CREATE SEQUENCE SEQ_TRANSACTION_TYPES
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 23667
  NOCYCLE
  CACHE 10;

INSERT INTO TRANSACTION_TYPES (ID, TRANSACTION_TYPE, DESCRIPTION)
  VALUES (SEQ_TRANSACTION_TYPES.nextval, 'STOCK PRICE INQUIRY', 'STOCK PRICE INQUIRY TRANSACTION');
INSERT INTO TRANSACTION_TYPES (ID, TRANSACTION_TYPE, DESCRIPTION)
  VALUES (SEQ_TRANSACTION_TYPES.nextval, 'STOCK PURCHASE', 'STOCK PURCHASE TRANSACTION');
INSERT INTO TRANSACTION_TYPES (ID, TRANSACTION_TYPE, DESCRIPTION)
  VALUES (SEQ_TRANSACTION_TYPES.nextval, 'STOCK SALE', 'STOCK SALE TRANSACTION');

COMMIT;
