
--------------------------------------------------------------------------------
-- create_application_parameters.sql
--------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA=STOCKS;

DROP TABLE APPLICATION_PARAMETER;
DROP SEQUENCE SEQ_APPLICATION_PARAMETER;

CREATE TABLE APPLICATION_PARAMETER (
  ID                NUMBER(10)                          NOT NULL PRIMARY KEY,
  PARAMETER_KEY     VARCHAR2(100)                       NOT NULL,
  PARAMETER_VALUE   VARCHAR2(500)                       NOT NULL,
  ENABLED           CHAR(1) DEFAULT 'Y'                 NOT NULL,
  CREATE_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) TABLESPACE tbs_users_01;

CREATE INDEX idx_app_parm_01 ON APPLICATION_PARAMETER (PARAMETER_KEY);

CREATE SEQUENCE SEQ_APPLICATION_PARAMETER
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;


INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.application.charsetutf8',
    'UTF-8',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.faultstr.client',
    'client',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.faultstr.server',
    'server',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.request.successful',
    'Request Successful',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.request.failed',
    'Request Failed',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.request.pending',
    'Request Pending',
    'Y', CURRENT_TIMESTAMP);
INSERT INTO APPLICATION_PARAMETER (ID, PARAMETER_KEY, PARAMETER_VALUE, ENABLED, CREATE_DATE)
  VALUES (SEQ_APPLICATION_PARAMETER.nextval,
    'parm.validation.requestheader.source',
    'STOCKTICKER_20170131',
    'Y', CURRENT_TIMESTAMP);

COMMIT;
