GRANT ALL ON STOCKS.APPLICATION_PARAMETER TO PUBLIC;
GRANT ALL ON STOCKS.APPLICATION_MESSAGES TO PUBLIC;
GRANT ALL ON STOCKS.ORDER_STATUS TO PUBLIC;
GRANT ALL ON STOCKS.ORDER_TYPES TO PUBLIC;
GRANT ALL ON STOCKS.STOCK_ORDER TO PUBLIC;
GRANT ALL ON STOCKS.STOCK_PRICE TO PUBLIC;
GRANT ALL ON STOCKS.STOCK_SYMBOL TO PUBLIC;
GRANT ALL ON STOCKS.TRANSACTION_LOG TO PUBLIC;
GRANT ALL ON STOCKS.TRANSACTION_TYPES TO PUBLIC;

