//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 08:58:08 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://project.mark.prv/stockservice/common/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package prv.mark.project.stockservice.common.schemas;
